name: Vite Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev/**'
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Print GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}

      - name: Print working directory
        run: echo $(pwd)

      - name: Setup Node.js
        uses: ./.github/workflows/node.js

      - name: Build with npm
        run: npm run build

      - name: List build outputs
        run: ls -lA dist/
